<?php

namespace AppBundle\Repository;

/**
 * ElevatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElevatorRepository extends \Doctrine\ORM\EntityRepository
{
}
